# Schema for the configuration files of the Access Task Module module.
access_task.settings:
  type: config_object
  label: 'Access Task Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
