<?php

/**
 * @file
 * Primary module hooks for CUstom Email Task Module module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_mail().
 */
function custom_email_task_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function custom_email_task_mail_alter(&$message) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
}

/**
 * Implements hook_entity_insert().
 */
function custom_email_task_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'page')) {

    $mailManager = \Drupal::service('plugin.manager.mail');

    $module = 'custom_email_task';
    $key = 'create_page';

    $config = \Drupal::config('custom_email_task.settings');

    $to = \Drupal::currentUser()->getEmail();

    $token_service = \Drupal::token();

    $subject = $config->get('subject');
    $message = $config->get('message')['value'];

    $sub_text = $token_service->replace($subject, ['node' => $entity], ['clear' => TRUE]);
    $msg_text = $token_service->replace($message, ['node' => $entity], ['clear' => TRUE]);

    $params['subject'] = $sub_text;
    $params['body'] = $msg_text;

    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $send = TRUE;

    $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
    if ($result['result'] !== TRUE) {

      \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
    }
    else {

      \Drupal::messenger()->addMessage(t('Your message has been sent.'), 'status');
      // drupal_set_message(t('Your message has been sent.'));.
    }

  }
}
